server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.8.196:3306/test_wangshuai?characterEncoding=UTF-8&useSSL=false
      username: root
      password: AwVspex2021#Db!
mybatis:
  mapper-locations: classpath:mapper/*.xml

